### PR TITLE
Issue 65

### PR DESCRIPTION
**Pull request by puneetbehl**
This pull request fixed Issue #65 to support specifying Google Maps API in a Config property `google.maps.key`

### CODE REVIEW

**Comment by robertoschwald** [comment]
Tested it locally. Works. Thanks for that.

**Comment by robertoschwald** [comment]
Updating the docs would be great.

**Comment by kousen** [comment]
Google Maps now requires a key. The pull request fixes that for Grails 3. Please merge. Even better would be to backport it to Grails 2 as well.

**Comment by puneetbehl** [comment]
I am working on that too

**Comment by aruizca** [comment]
Version 2.2 released with this patch included.
Thanks @puneetbehl !!

**Comment by puneetbehl** [comment]
@robertoschwald @kousen Following is the draft version of https://puneetbehl.github.io/grails-google-visualization/[documentation]. I will send pull request for same shortly.

Also, please let me know if you think we are missing anything in documentation.

**Comment by robertoschwald** [comment]
Great! I like it.

**Pull request merged**
