### PR TITLE
removed url mappings

### PR DESCRIPTION
**Pull request by ZacharyKlein**
This PR removes the plugin's default URL mappings to avoid potential conflicts within an application. The mappings don't seem to be adding anything in particular to the application. 

Alternatively, the url mapping file could be renamed to `UrlMappings.groovy` and then it would be excluded from the packaged plugin, which would also work in our case.

Thanks!

### CODE REVIEW

**Comment by aruizca** [comment]
Please have a look at issue #63

**Comment by jeffbrown** [comment]
The mappings defined in `GrailsGoogleVisualizationUrlMappings.groovy` will make their way into the application.  The plugin should not be providing mappings like `/` in that file.  Further, having the wild carded `"/$controller/$action?/$id?(.$format)?"` in the plugin should be considered a security violation.  That mapping is convenient in the early stages of development but most production apps should remove that.  Having the plugin impose that mapping on the application means that most applications would not be able to use this plugin.  

The mappings defined in this `GrailsGoogleVisualizationUrlMappings.groovy` file are not mappings that the plugin should be imposing on an app.  As far as I can tell, there are no mappings that this particular plugin should be imposing on apps.  `GrailsGoogleVisualizationUrlMappings.groovy` should be removed.  If the plugin wants to contain a `UrlMappings.groovy` file of its own just for testing the plugin, that would be fine.

**Comment by jeffbrown** [comment]
Can we have this PR applied and get a release published?  I don't want to fork the plugin just to remove this file, but we need it removed.

**Comment by aruizca** [comment]
Hi @jeffbrown 
Sorry for this, but I was misled to belief the contrary in a previous PR as mentioned in a previous comment. My bad because I should have double check it.
I will revert the changes made so the file gets renamed to UrlMappings.groovy ASAP
If I have not done it already is because I am in a different timezone. No need to threaten
Cheers

**Comment by aruizca** [comment]
Done (y)

**Comment by robertoschwald** [comment]
As written in #63, removing the file is the way to go. Thanks for that.

**Comment by aruizca** [comment]
Thanks @robertoschwald, 
According to @jeffbrown I can leave the file as UrlMappings.groovy. I need that to execute the plugin test pages.

**Comment by jeffscottbrown** [comment]
@aruizca "No need to threaten" - I wasn't threatening.  I am sorry that you misunderstood me.  I was just saying that we needed a version of the plugin that didn't contain this mapping file and I didn't want to have to fork it just for that.  If you were opposed to making the change then we would respect that and we would just have to fork the code and maintain a separate version.  I really didn't mean it as a threat.

**Comment by aruizca** [comment]
@jeffbrown No worries. I have released 2.2.1. Please let me know if you need anything else

**Pull request closed without merging**
